import os

def main():
    print("===========================================")
    print("      TikTok Scraper Configuration Helper")
    print("===========================================")
    print("It looks like your configuration file is a bit messy.")
    print("I will help you fix it by asking for each key one by one.")
    print("Just paste the value and press Enter.")
    print("===========================================\n")

    # 1. Database URL
    print("1. DATABASE_URL")
    print("   (The one starting with 'postgresql://...')")
    database_url = input("   Paste here: ").strip()
    
    # 2. Supabase URL
    print("\n2. SUPABASE_URL")
    print("   (The one starting with 'https://...')")
    supabase_url = input("   Paste here: ").strip()
    if not supabase_url and database_url:
        # Try to extract from DB URL if empty
        try:
            # db.xyz.supabase.co -> https://xyz.supabase.co
            parts = database_url.split('@')[1].split(':')[0] # db.xyz.supabase.co
            project_ref = parts.split('.')[1] # xyz
            supabase_url = f"https://{project_ref}.supabase.co"
            print(f"   (Auto-detected: {supabase_url})")
        except:
            pass

    # 3. Supabase Anon Key
    print("\n3. SUPABASE_ANON_KEY")
    print("   (The long string in Project Settings -> API. NOT 'sbp_...')")
    anon_key = input("   Paste here: ").strip()

    # 4. Supabase Service Role Key
    print("\n4. SUPABASE_SERVICE_ROLE_KEY")
    print("   (The other long string in Project Settings -> API)")
    service_role_key = input("   Paste here: ").strip()

    # 5. OpenAI API Key
    print("\n5. OPENAI_API_KEY")
    print("   (Starting with 'sk-proj-...')")
    openai_key = input("   Paste here: ").strip()

    # Write to .env
    env_content = f"""# Generated by Configuration Helper
SUPABASE_URL={supabase_url}
SUPABASE_ANON_KEY={anon_key}
SUPABASE_SERVICE_ROLE_KEY={service_role_key}
DATABASE_URL={database_url}
OPENAI_API_KEY={openai_key}
"""
    
    # Adjust path to root
    env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.env')
    
    with open(env_path, 'w') as f:
        f.write(env_content)
        
    print("\n===========================================")
    print("✅ Configuration saved successfully!")
    print(f"File updated: {env_path}")
    print("You can now close this window and run start_app.bat")
    print("===========================================")
    input("Press Enter to exit...")

if __name__ == "__main__":
    main()
